# Indexing & Slicing

In [7]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(a1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a1[4]


5

In [12]:
a1[-5]

5

In [13]:
a1[:3]

array([1, 2, 3])

In [14]:
a1[6:]

array([7, 8, 9])

In [17]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1[2:5]

array([3, 4, 5])

In [19]:
a1[::3]

array([1, 4, 7])

In [20]:
a1[1::2]

array([2, 4, 6, 8])

In [22]:
a1[1:-3:2]

array([2, 4, 6])

# Fancy Indexing 

In [24]:
a1[[0,4,6,-1]]

array([1, 5, 7, 9])

In [ ]:
a2= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(a2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [28]:
a2[1,0]

40

In [30]:
a2[-2,1]

50

In [31]:
a2[0,:]

array([10, 20, 30])

In [32]:
a2[0]

array([10, 20, 30])

In [34]:
a2[:,1]

array([20, 50, 80])

In [35]:
a2[0:3:2,0:3:2]

array([[10, 30],
       [70, 90]])

In [36]:
a2[:3:2,:3:2]

array([[10, 30],
       [70, 90]])

In [38]:
a3= np.array([
    [[10,20,30],
    [40,50,60],
    [70,80,90]],
     
    [[10,20,30],
    [40,50,60],
    [70,80,90]]])
print(a3)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [39]:
a3[1,0,1]

20

In [40]:
a3[:,1:3,:]

array([[[40, 50, 60],
        [70, 80, 90]],

       [[40, 50, 60],
        [70, 80, 90]]])

In [41]:
a3[:,1:3,::2]

array([[[40, 60],
        [70, 90]],

       [[40, 60],
        [70, 90]]])

# Boolian Indexing

In [43]:
print(a3)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [44]:
a3[a3>50]

array([60, 70, 80, 90, 60, 70, 80, 90])