# Array Manipulation

In [65]:
import numpy as np

In [66]:
a1 = np.array([1,2,3,4,5,6,7,8,9])

a2= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

a3= np.array([
    [[10,20,30],
    [40,50,60],
    [70,80,90]],
     
    [[10,20,30],
    [40,50,60],
    [70,80,90]]])


# Size Of Array

In [67]:
a1.size

9

In [68]:
a2.size

9

In [69]:
a3.size

18

# # Shape Of Array

In [70]:
a1.shape

(9,)

In [71]:
a3.shape

(2, 3, 3)

# Dimention Of Array

In [72]:
a3.ndim

3

In [73]:
a2.ndim

2

# np.may_share_memory()

NumPy to check if two arrays might share the same memory block

# Flattening Of Array


Returns a copy of the original array

Modifying the flattened array does NOT affect the original

Always returns a 1D array


In [74]:
a3_b=a3.flatten()
a3_b

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 10, 20, 30, 40, 50, 60, 70, 80,
       90])

In [75]:
np.may_share_memory(a3,a3_b)

False

# Ravel of Array

Returns a view (if possible); i.e., no data is copied

Modifying it may affect the original (if it's a view)

Faster than flatten() because it avoids copying when possible

In [76]:
a3_b=a3.ravel()

In [77]:
np.may_share_memory(a3,a3_b)

True

In [78]:
a3

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

# Reshape of Array
Total number of elements must remain the same before and after reshaping.      
"To reshape an array, total elements must match — choose two numbers that multiply to that total."

In [79]:
a3_c=a3

In [80]:
a3=a3_c.ravel()


In [81]:
a3.reshape(3,3,2)

array([[[10, 20],
        [30, 40],
        [50, 60]],

       [[70, 80],
        [90, 10],
        [20, 30]],

       [[40, 50],
        [60, 70],
        [80, 90]]])

In [82]:
a3_c.reshape(2,3,3).copy()

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [83]:
a3=a3_c.flatten()

In [84]:
np.may_share_memory(a3,a3_c)

False

# Expend Dimention
Add extra 1 dimention by axis=? where u want

In [85]:
a2.shape

(3, 3)

In [86]:
np.expand_dims(a2,axis=0).shape

(1, 3, 3)

In [87]:
np.expand_dims(a2,axis=2).shape

(3, 3, 1)

# Squeeze Dimention
squeeze() is used to remove dimensions of size 1 from an array's shape.

In [88]:
np.squeeze(a2).shape

(3, 3)

# Stak
joins multiple arrays along a new axis.

In [89]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([11,22,33,44,55,66,77,88,99,100])

In [90]:
np.vstack((a,b))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100]])

In [91]:
np.hstack((b,a))

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100,   1,   2,   3,
         4,   5,   6,   7,   8,   9,  10])

# Split of Array
Strict splitting: You must split the array into equal-sized chunks.

❌ Throws an error if the array can't be divided exactly.



In [92]:
np.split(b,5)

[array([11, 22]),
 array([33, 44]),
 array([55, 66]),
 array([77, 88]),
 array([ 99, 100])]

In [93]:
c = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,2,3,4,5,6,8,3,4,5,6,7,3,4,5,6,7])

# array_split()
✅ Flexible splitting: It allows unequal chunk sizes.

No error if split is not exact — it just balances as evenly as possible.

In [94]:
np.array_split(c,9)

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([9, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([8, 2, 3, 4]),
 array([5, 6, 8, 3]),
 array([4, 5, 6]),
 array([7, 3, 4]),
 array([5, 6, 7])]

# Delete
it return new array.

In [95]:
d = np.delete(c,4)
d

array([1, 2, 3, 4, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 8,
       3, 4, 5, 6, 7, 3, 4, 5, 6, 7])

# Insurt

In [96]:
e = np.insert(a,2,11)
e

array([ 1,  2, 11,  3,  4,  5,  6,  7,  8,  9, 10])