# NumPy (Numerical Python) is a Python library used for fast mathematical operations on large arrays and matrices

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6,7,8,9,0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
np.array([
    [1,2,3],
    [4,5,6]
    ])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.array([[[1,2,3],
           [1,2,3],
           [1,2,3]],
           
           [[1,2,3],
           [1,2,3],
           [1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full(5,4)

array([4, 4, 4, 4, 4])

In [21]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

#  Identity Matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Diagonal Matrix

In [25]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Range Matrix 

In [26]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Range Matrix skip 2

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# Linespace in 2 number

In [29]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

Randam Array

In [31]:
np.random.rand(2,3)

array([[0.88898413, 0.49591611, 0.56902969],
       [0.02682617, 0.10876498, 0.45837073]])

In [32]:
np.random.rand(3,4)

array([[0.58614593, 0.82487149, 0.72954744, 0.32775492],
       [0.08791579, 0.64606592, 0.71271895, 0.66639176],
       [0.7252934 , 0.36886735, 0.76640865, 0.27761431]])

In [33]:
np.random.rand(2,3,4)

array([[[0.62184875, 0.05223696, 0.81297201, 0.74487564],
        [0.49949203, 0.0297699 , 0.4366514 , 0.43074788],
        [0.12871346, 0.76677438, 0.74203418, 0.72741391]],

       [[0.15834325, 0.02727695, 0.80744775, 0.49893781],
        [0.30461078, 0.18862594, 0.87021999, 0.62048571],
        [0.89960588, 0.62892858, 0.09374958, 0.39783492]]])

# Random Array in a given range of Number and Dimentions

In [36]:
np.random.randint(1,100,(3,5))

array([[66, 21, 81, 34, 90],
       [40,  3, 43, 62, 30],
       [81, 39, 42,  2, 41]])

# Random Array with Choice

In [38]:
np.random.choice([1,5,10,15,20,25,30,35,40,45,50],(3,2))

array([[ 5, 20],
       [30, 20],
       [15, 40]])

# List convert to Numpy Array

In [39]:
li = [10,20,30,40,50,60,70,80,90]

In [40]:
np.array(li)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Tuple convert to Numpy Array

In [41]:
tup = (10,20,30,40,50,60,70,80,90)

In [42]:
np.array(tup)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# set convert to Numpy Array

In [43]:
st = {10,20,30,40,50,60,70,80,90} 

In [44]:
np.array(st)

array({70, 40, 10, 80, 50, 20, 90, 60, 30}, dtype=object)